name: Metrics
on:
  # Se actualiza cada día a media noche
  schedule: [{cron: "0 0 * * *"}]
  # Se actualiza si haces un push manual
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuración de Usuario
          user: Sama170904
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: America/Guayaquil
          
          # Plugins para datos estilo "Neofetch"
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
